FROM ubuntu:22.04

ARG TARGETARCH

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY bin/linux_${TARGETARCH}/secret-reader /app/secret-reader

RUN chmod +x /app/secret-reader

EXPOSE 3000

USER 1000

ENTRYPOINT ["/app/secret-reader"]