apiVersion: v1
kind: Service
metadata:
  name: secret-reader
  labels:
    app: secret-reader
spec:
  type: ClusterIP
  selector:
    app: secret-reader
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
